services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - appnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/plataforma_assinatura?schema=public
      - JWT_SECRET=supersegredo
      - JWT_EXPIRATION=1d
      - UPLOAD_DIR=/app/uploads
    volumes:
      - backend_uploads:/app/uploads
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - appnet

volumes:
  db_data:
  backend_uploads:

networks:
  appnet: