services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./database/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d plataforma_assinatura"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - appnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - backend_uploads:/app/uploads
      # - ./backend:/app
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - appnet
    # volumes:
    #   - ./frontend:/app

volumes:
  db_data:
  backend_uploads:

networks:
  appnet:
